### PR TITLE
SLING-9060 Improved handling of redirects when streaming

### PR DESCRIPTION
**Pull request by ieb**
Depends on https://github.com/apache/sling-org-apache-sling-api/pull/17 being released.

Implements better handling of redirects using he RedirectResolver provider API

### CODE REVIEW

**Review by cziegeler — COMMENTED** [review]
Lgtm, thanks - please see my comments on the api

**Comment by ieb** [comment]
depends on the API and won't build till that is merged.

**Comment by ieb** [comment]
API PR was -1

**Comment by ieb** [comment]
trying again with interface approach.

**Comment by cziegeler** [comment]
Issue got resolved wont fix some time ago, closing PR

**Pull request closed without merging**
